#!/usr/bin/env python
"""
Parse every FASTA record from stdin and print each.
"""

# any idea how to make module

import fasta_Reader
import sys

        
# What I want:

reader = fasta_Reader.FASTAReader( sys.stdin )


for identifier, sequence in reader:
        print identifier, sequence

    
    
    
    
    
    
    
