#!/usr/bin/env python
"""
read sequences from a FASTA file, count the number of times each k-mer occurs across 
samples and print
kmers and counts.

usage: 00-kmercounter.py k > fasta_file

"""

# read each sequence from FASTA, parse parameters, k 
# read data, FASTA parser
# where to store kmer counts
# length = n
# kmer = sequence[i:i+k]
## 
#kmer_counts = dictionary{}

import sys
import fasta2

#command line arguments
k = int(sys.argv[1]) 


#i have the kmer at position i, if ive seen the kmer, it sets to 0. if i have seen it, 
for ident, sequence in fasta2.FASTAReader(sys.stdin):
    sequence = sequence.upper()
    kmercounts = {}
    for i in range(0, len(sequence)-k):
        kmer = sequence[i: i+k]
        if kmer not in kmercounts:
            kmercounts[kmer] = 0
        kmercounts[kmer] += 1
    print "---", ident, "---"

#take this but do it for each fasta file
    for i, kmer in enumerate(sorted(   kmercounts, 
                                    key = kmercounts.get, 
                                    reverse = True)):                        
        if i > 10:
            break
        print kmer, kmercounts[kmer]

 

